name: Publish Alpha Version

on:
  pull_request:
    types:
      - closed
    branches:
      - next

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure NPM Registry (Artifactory)
        run: |
          npm set always-auth true
          npm set email shawntompke@gmail.com
          npm i -g npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install 
      - name: Publish NPM Alpha Release
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna publish --conventional-commits --canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
