name: Publish Alpha Version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  publish-npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure NPM Registry (Artifactory)
        run: |
          npm set always-auth true
          npm set email shawntompke@gmail.com
          npm i -g npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install 
      - name: setup nvmrc
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
          
      - name: Set version history
        id: random-color-generator2
        run: |
          echo "SELECTED_COLOR<<EOF" >> $GITHUB_OUTPUT
          echo "$(npx lerna list -l)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: SHOW VERSIONS
        run: echo "${{ steps.random-color-generator2.outputs.SELECTED_COLOR }}"
          
      - name: Create Release Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version --conventional-commits --create-release github -m "chore(release): publish" --no-private --exact --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GIT_TOKEN}}
          
      - name: They matched!
        if: ${{steps.random-color-generator2.outputs.SELECTED_COLOR}} == $(npx lerna list -l)
        run: echo "THEY MATCHED!"        
        
      - name: They DIDNT match!
        if: ${{steps.random-color-generator2.outputs.SELECTED_COLOR}} != $(npx lerna list -l)
        run: echo "THEY DID NOT MATCH!"        

      - name: Publish Stable Release to NPM
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna publish from-package --conventional-commits --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
