name: Publish Alpha Version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    if: github.event.inputs.forcePublish == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure NPM Registry (Artifactory)
        run: |
          npm set always-auth true
          npm set email shawntompke@gmail.com
          npm i -g npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install 
      - name: Create Release Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version --conventional-commits --create-release github -m "chore(release): publish" --no-private --exact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Stable Release to NPM
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna publish from-package --conventional-commits
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
