name: Publish Alpha Version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  publish-npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure NPM Registry (Artifactory)
        run: |
          npm set always-auth true
          npm set email shawntompke@gmail.com
          npm i -g npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install 
      - name: setup nvmrc
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
          
      - id: project-name
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^[a-z]+\(([a-zA-Z\-]+)\):.+$'
          
      - name: show project name
        run: |
          echo ${{ steps.project-name.outputs.group1 }}
          
      - name: Pre Lerna Version
        id: before-versions
        run: |
          echo "VERSION<<EOF" >> $GITHUB_OUTPUT
          echo "$(npx lerna list -l)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: Show Before Versions
        run: echo "${{ steps.before-versions.outputs.VERSION }}"
          
      - name: Create Release Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version --conventional-commits --create-release github -m "chore(release): publish" --no-private --exact --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GIT_TOKEN}}
          
      - name: After Lerna Version
        id: after-versions
        run: |
          echo "VERSION<<EOF" >> $GITHUB_OUTPUT
          echo "$(npx lerna list -l)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: SHOW VERSIONS
        run: echo "${{ steps.after-versions.outputs.VERSION }}"
          
      - name: Versions Matched
        if: ${{steps.before-versions.outputs.VERSION == steps.after-versions.outputs.VERSION}}
        run: echo "THEY MATCHED!"        
        
      - name: Versions Didnt Match
        if: ${{steps.before-versions.outputs.VERSION != steps.after-versions.outputs.VERSION}}
        run: echo "THEY DID NOT MATCH!"

      - name: Publish Stable Release to NPM
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna publish from-package --conventional-commits --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
