name: Test lerna version

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: thingy
        id: detect-changes-between-two-branches
        run: |
          source_ahead=npx lerna list -l
          echo "is-source-branch-ahead=$source_ahead" >> $GITHUB_OUTPUT
          
      - name: echo thingy
        run: |
          echo "${{steps.detect-changes-between-two-branches.outputs.is-source-branch-ahead}}"

#       - name: Configure NPM Registry (Artifactory)
#         run: |
#           npm set always-auth true
#           npm set email shawntompke@gmail.com
#           npm i -g npm
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - name: Install dependencies
#         run: npm install
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#       - name: Install dependencies
#         run: npm install 
#       - name: setup nvmrc
#         run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - name: Create Release Tag
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           npx lerna version --conventional-commits --create-release github -m "chore(release): publish" --no-private --exact --yes
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           GH_TOKEN: ${{secrets.GIT_TOKEN}}
#       - name: Publish Stable Release to NPM
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           npx lerna publish from-package --conventional-commits --yes
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
